### PR TITLE
Add 'Show/Hide all' button as a dummy series object and hide its icon via CSS

### LINKED ISSUE #10: Toggle all/none client items in highcharts diagram
as i have quite a few clients in my chart, it would be nice to have a toggle (or checkmark) like "show all clients"/"show no clients". right now i have to click every client manually.

i might do a pull request if i find some time.

### PR DESCRIPTION
**Pull request by nakami**
Resolves #10.

### CODE REVIEW

**Comment by phiresky** [comment]
mh you should make sure the typescript types are correct, the type of chart should be Highcharts.Chart not `{}`. otherwise looks good

**Comment by phiresky** [comment]
github is buggy. this pr is merged, though github doesn't show it

**Comment by phiresky** [comment]
thanks!

**Comment by nakami** [comment]
Also, the corresponding issue did not close by itself (like it should): https://github.com/phiresky/nmap-log-parse/issues/10

But that may be just the result of the bug you mentioned.

**Pull request closed without merging**
