### PR TITLE
standard HTML syntax

### PR DESCRIPTION
**Pull request by AdamHess**
Wrapped the content in a body tag, wrapped the document in an HTML tag and
wrapped the style and script tags in a head tag.

### CODE REVIEW

**Comment by phiresky** [comment]
Mh. I decided a while ago to never use those tags in my projects for these reasons:
- Don't need a template when starting / less boilerplate code
- the official standard calls them optional, the w3 validator (http://validator.w3.org) shows it as correct
- the google styleguide recommends leaving them out (http://stackoverflow.com/a/25749523/2639190)
- I don't like having the body of a document on an already indented level.

If you have strong arguments in favor of adding the wrapping tags, I'm willing to change my mind.

Oh and the title tag is not optional and was missing here, I added that.

**Comment by AdamHess** [comment]
It's more following conventions than anything else. 

the head tag is typically holds all HTML and CSS references. 

Body tag - all the stuff on your page 

html - that you could leave out, but I wouldn't. Most developers get wonky when they dont see it.

**Comment by phiresky** [comment]
Yeah, I know. But browsers do add those tags perfectly fine on their own(, and I like minimalism).

So I'm not sure, doesn't seem like that good of an argument to me. And as linked, it's also a convention to leave them out for a different group of people.

**Comment by AdamHess** [comment]
alrighty, aaaand you lost a contributor.

**Comment by AdamHess** [comment]
aaaaand, I'm out.

**Comment by phiresky** [comment]
Sorry, but if you don't come forward with any actual reason.. Not like I have that strong of an opinion about it, so feel free to work on your fork and I'll merge, including style changes, when you have something that adds a feature / removes a bug.

**Pull request closed without merging**
